name: Gerar APK Ponto Obra
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerar arquivos do Gradle oficiais
        run: |
          rm -f gradlew
          rm -rf gradle
          wget -q https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip -q gradle-8.5-bin.zip
          ./gradle-8.5/bin/gradle wrapper
          chmod +x gradlew
          rm -rf gradle-8.5 gradle-8.5-bin.zip

      - name: Compilar APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Salvar APK pronto
        uses: actions/upload-artifact@v4
        with:
          name: APK-Pronto
          path: app/build/outputs/apk/debug/*.apk
